### ISSUE TITLE
[TODO LIST] 4.0.5.0 Release

### ISSUE THREAD

**Issue by sandtechnology** [Ghost-chu/QuickShop-Reremake#575]
### Improvement 
- [x] Handle ALL SQL operation in DatabaseManager to prevent connection competing issue (#567, may related to shop missing issue).
- [x] Setting display-type to 0 by default, and warn when using other display type on 1.16+ server.
- [x] Use color code to recognize shop sign, instead owner name (Sometime it will be changed, and getOfflinePlayerName is a time-consuming operation).
- [ ] ~~Refactor integration function, replace method-based to event-based.~~(Cancel due to is not needed)
- [x] (Optional) Combine `example.config.yml` and `config.yml`, lots of new users never notice this.(Change to make more attractive tips for uses)
- [x] (Optional) Re-do find command (#490, #391)
### Features
- [x] Support split large log file, compress it like server log.
- [x] Support sending out-stock message to staffs.
- [x] Support removing shop automatically when plugin area was removed.(Towny ONLY due to it will have bypass problem)
- [ ] ~~Support managing shop by the owner or moderator of the plugin area.(Help wanted, it will need iterator for owner for every time)~~(Skipping, it needs refactor owner system)
- [ ] ~~Support detecting conflict chat plugin (e.g. sending a message but not working or saying is an invalid message)~~(Cancel due to is not needed)
### Other
- [x] #548 
### Addon
- [ ] #469
- [ ] #489
- [ ] #376

**Comment by Ghost-chu** [comment]
```
Use color code to recognize shop sign, instead owner name (Sometime it will be changed, and getOfflinePlayerName is a time-consuming operation).
That not a good idea if owner changed the format in messages.yml.
```

**Comment by sandtechnology** [comment]
> 
> 
> ```
> Use color code to recognize shop sign, instead owner name (Sometime it will be changed, and getOfflinePlayerName is a time-consuming operation).
> That not a good idea if owner changed the format in messages.yml.
> ```

It will be hardcode in the code, so it's OK

**Comment by sandtechnology** [comment]
Which color code will be OK to use?

**Comment by Ghost-chu** [comment]
closed due we migrate to use milestone
